p8105_hw1_yc4384
================
Yangyang Chen
2023-09-17

## Problem_1

\#Introduce the dataset

``` r
library(moderndive)
data("early_january_weather") #load dataset
summary(early_january_weather) #the variables in this dataset, including names / values of important variables
```

    ##     origin               year          month        day              hour      
    ##  Length:358         Min.   :2013   Min.   :1   Min.   : 1.000   Min.   : 0.00  
    ##  Class :character   1st Qu.:2013   1st Qu.:1   1st Qu.: 4.000   1st Qu.: 6.00  
    ##  Mode  :character   Median :2013   Median :1   Median : 8.000   Median :11.50  
    ##                     Mean   :2013   Mean   :1   Mean   : 8.039   Mean   :11.53  
    ##                     3rd Qu.:2013   3rd Qu.:1   3rd Qu.:12.000   3rd Qu.:17.75  
    ##                     Max.   :2013   Max.   :1   Max.   :15.000   Max.   :23.00  
    ##                                                                                
    ##       temp            dewp           humid           wind_dir    
    ##  Min.   :24.08   Min.   : 8.96   Min.   : 32.86   Min.   :  0.0  
    ##  1st Qu.:33.98   1st Qu.:19.94   1st Qu.: 51.34   1st Qu.:140.0  
    ##  Median :39.02   Median :26.06   Median : 61.67   Median :240.0  
    ##  Mean   :39.58   Mean   :28.06   Mean   : 65.48   Mean   :208.2  
    ##  3rd Qu.:44.96   3rd Qu.:35.06   3rd Qu.: 78.68   3rd Qu.:290.0  
    ##  Max.   :57.92   Max.   :53.06   Max.   :100.00   Max.   :360.0  
    ##                                                   NA's   :5      
    ##    wind_speed       wind_gust         precip            pressure   
    ##  Min.   : 0.000   Min.   :16.11   Min.   :0.000000   Min.   :1011  
    ##  1st Qu.: 5.754   1st Qu.:19.56   1st Qu.:0.000000   1st Qu.:1018  
    ##  Median : 8.055   Median :21.86   Median :0.000000   Median :1022  
    ##  Mean   : 8.226   Mean   :22.53   Mean   :0.002039   Mean   :1023  
    ##  3rd Qu.:11.508   3rd Qu.:25.32   3rd Qu.:0.000000   3rd Qu.:1027  
    ##  Max.   :24.166   Max.   :31.07   Max.   :0.190000   Max.   :1034  
    ##                   NA's   :308                        NA's   :38    
    ##      visib          time_hour                     
    ##  Min.   : 0.120   Min.   :2013-01-01 01:00:00.00  
    ##  1st Qu.: 9.000   1st Qu.:2013-01-04 19:15:00.00  
    ##  Median :10.000   Median :2013-01-08 12:30:00.00  
    ##  Mean   : 8.515   Mean   :2013-01-08 12:28:09.39  
    ##  3rd Qu.:10.000   3rd Qu.:2013-01-12 05:45:00.00  
    ##  Max.   :10.000   Max.   :2013-01-15 23:00:00.00  
    ## 

- There are 15 variables in the dataset. The variable ‘origin’ is an
  character type variable, and variable ‘wind_gust’ includes all NA
  values.
- The dataset has 358 rows and 15 columns.
- The mean of ‘temp’ is 39.58.

``` r
#Scatterplot of dataset and save image
library(ggplot2)
scatter_plot = ggplot(early_january_weather, aes(x = time_hour, y= temp, color = humid)) #color points using the humid variable
scatter_plot + geom_point()
```

![](p8105_hw1_yc4384_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

- The temperature is non-stationary, and it is periodically fluctuated
  increasing from Jan_01 to Jan_15.

``` r
ggsave("scatterplot.png", plot = scatter_plot + geom_point(), width = 6, height = 4) #Export scatterplot to the project directory
```

## Problem_2

``` r
#Create a dataset
v1 = rnorm(10) #a random sample of size 10 from a standard Normal distribution
v2 = ifelse(v1>0, "T", "F") #a logical vector indicating whether elements of the sample are greater than 0
v3 = c('a','b','c','d','e','f','g','h','i','j') #a character vector of length 10
v4 = as.factor(c(1,2,3,3,2,1,2,3,1,3)) #a factor vector of length 10, with 3 different factor “levels”
df = data.frame(v1,v2,v3,v4) #create a data frame
df
```

    ##             v1 v2 v3 v4
    ## 1   0.53938322  T  a  1
    ## 2   0.05687582  T  b  2
    ## 3   1.77571543  T  c  3
    ## 4  -0.48520543  F  d  3
    ## 5   2.48446293  T  e  2
    ## 6   1.26753278  T  f  1
    ## 7   0.09802929  T  g  2
    ## 8  -1.73143824  F  h  3
    ## 9   0.27633990  T  i  1
    ## 10 -0.34926902  F  j  3

``` r
#Compute mean of each vector
library(tidyverse)# Use pull() to extract the each column as a vector
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ lubridate 1.9.2     ✔ tibble    3.2.1
    ## ✔ purrr     1.0.2     ✔ tidyr     1.3.0
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
vector <- df %>% pull(v1)
mean(vector)
```

    ## [1] 0.3932427

``` r
vector <- df %>% pull(v2)
mean(vector)
```

    ## Warning in mean.default(vector): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

``` r
vector <- df %>% pull(v3)
mean(vector)
```

    ## Warning in mean.default(vector): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

``` r
vector <- df %>% pull(v4)
mean(vector)
```

    ## Warning in mean.default(vector): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

``` r
# Convert variables from one type to another and calculate their means
vector <- df %>% pull(v2)
mean(as.numeric(as.factor(vector)))
```

    ## [1] 1.7

``` r
vector <- df %>% pull(v3)
mean(as.numeric(as.factor(vector)))
```

    ## [1] 5.5

``` r
vector <- df %>% pull(v4)
mean(as.numeric(vector))
```

    ## [1] 2.1

- Since v2 and v3 are converted to numeric values. their means can be
  computed.
